# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Homepage(object):
    def setupUi(self, Form):
        pixmap = QtGui.QPixmap("pages_ui/image/background-2.png")
        palette = Form.palette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(pixmap))
        Form.setPalette(palette)
        Form.setObjectName("Form")
        Form.resize(750, 450)
        Form.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"font-size:24px;\n"
"}\n"
"QFrame{\n"
"border-radius:30px;\n"
"background:rgba(236, 197, 233, 0.5);n"
"}\n"
"\n"
"QPushButton{\n"
"background:#ecc5e9;\n"
"border-radius:15px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:white;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(120, 89, 500, 291))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 130, 351, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.fiyat_al = QtWidgets.QPushButton(self.frame)
        self.fiyat_al.setGeometry(QtCore.QRect(270, 120, 171, 51))
        self.fiyat_al.setObjectName("fiyat_al")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "FİYAT BİLGİSİ İÇİN "))
        self.fiyat_al.setText(_translate("Form", "TIKLAYINIZ."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui =  Ui_Form_Homepage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
