# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Create_User(object):
    def setupUi(self, Form):
        pixmap = QtGui.QPixmap("pages_ui/image/background-2.png")
        palette = Form.palette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(pixmap))
        Form.setPalette(palette)
        Form.setObjectName("Form")
        Form.resize(770, 450)
        Form.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"font-size:30px;\n"
"\n"
"}\n"
"#label_text{\n"
"font-size:13px;\n"
"background-color: transparent;\n"
"}\n"
"#label_bilgi{\n"
"font-size:20px;\n"
"color:white;\n"
"}\n"
"#label_sonuc{\n"
"font-size:25px;\n"
"font-weight: bold;\n"
"color:white;\n"
"}\n"
"QFrame{\n"
"border-radius:15px;\n"
"background:#6495ed;\n"
"}\n"
"#label_title{\n"
"background:#ecc5e9;\n"
"}\n"
"#Form{\n"
"background:url(:/image/icon/background-2.png);\n"
"}\n"
"QPushButton{\n"
"background:#ecc5e9;\n"
"border-radius:15px;\n"
"font-family:century gothic;\n"
"font-size:25px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:white;\n"
"}\n"
"\n"
"#button2:hover{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:rgba(236, 197, 233, 0.5);\n"
"}\n"
"\n"
"#button2{\n"
"background:transparent;\n"
"font-size:15px;\n"
"border: 2px solid #000;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"color:#ecc5e9;\n"
"border:none;\n"
"border-bottom:2px solid #ecc5e9;\n"
"background:transparent;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(120, 110, 511, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_username = QtWidgets.QLabel(self.frame)
        self.label_username.setGeometry(QtCore.QRect(50, 90, 181, 41))
        self.label_username.setObjectName("label_username")
        self.label_2_password = QtWidgets.QLabel(self.frame)
        self.label_2_password.setGeometry(QtCore.QRect(50, 150, 181, 41))
        self.label_2_password.setObjectName("label_2_password")
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_username.setGeometry(QtCore.QRect(240, 90, 161, 41))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_2_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2_password.setGeometry(QtCore.QRect(240, 150, 161, 41))
        self.lineEdit_2_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2_password.setObjectName("lineEdit_2_password")
        self.pushButton_create = QtWidgets.QPushButton(self.frame)
        self.pushButton_create.setGeometry(QtCore.QRect(380, 270, 111, 31))
        self.pushButton_create.setObjectName("pushButton_create")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(120, 40, 511, 41))
        self.label_title.setObjectName("label_title")
        self.button2 = QtWidgets.QPushButton("geri", Form)
        self.button2.setObjectName("button2")

        # self.button2.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.button2.setFixedSize(80,25)
        self.button2.setGeometry(QtCore.QRect(130, 400, 111, 31))
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_username.setText(_translate("Form", "Username :"))
        self.label_2_password.setText(_translate("Form", "Password  :"))
        self.pushButton_create.setText(_translate("Form", "Create"))
        self.label_title.setText(_translate("Form", "               CREATE ACCOUNT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_Create_User()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
