# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        pixmap = QtGui.QPixmap("pages_ui/image/background-2.png")
        palette = Form.palette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(pixmap))
        Form.setPalette(palette)
        Form.setObjectName("Form")
        Form.resize(750, 450)
        Form.setMinimumSize(750, 450)
        Form.setMaximumSize(750, 450)
        Form.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"font-size:24px;\n"
"}\n"
"QFrame{\n"
"border-radius:15px;\n"
"background:rgba(236, 197, 233, 0.5);n"
"}\n"
"\n"
"#Form{\n"
"background:url('pages_ui/image/background-2.png');\n"
"}\n"
"QPushButton{\n"
"background:#ecc5e9;\n"
"border-radius:15px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"border-radius:15px;\n"
"background:white;\n"
"}\n"
"\n"
"#button_create_user{\n"
"background:transparent;\n"
"font-size:15px;\n"
"border-bottom: 2px solid #000;"
"border-radius: 15px;\n"
"}\n"
"\n"
"#button_create_user:hover{\n"
"background:rgba(236, 197, 233, 0.5);\n"
"}\n"
"\n"
"QToolButton{\n"
"background:#ecc5e9;\n"
"border-radius:10px;\n"
"padding: 3px 3px;\n"
"\n"
"}\n"
"QLabel{\n"
"color:black;\n"
"}\n"
"QLineEdit{\n"
"color:black;\n"
"border:none;\n"
"border-bottom:2px solid #ecc5e9;;\n"
"background:transparent;\n"
"\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(170, 80, 371, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(30, 120, 311, 31))
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(30, 180, 311, 31))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setGeometry(QtCore.QRect(360, 380, 211, 51))
        self.pushButton_login.setObjectName("pushButton_login")
        self.button_create_user = QtWidgets.QPushButton("Create Account",Form)
        self.button_create_user.setGeometry(QtCore.QRect(180, 385, 311, 20))
        self.button_create_user.setFixedSize(150,25)
        self.button_create_user.setStyleSheet("QPushButton {border-radius: 30px;}")
        self.button_create_user.setObjectName("button_create_user")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(300, 30, 121, 111))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pages_ui/image/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(70, 70))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton_login.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
