# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messages.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Message(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 321)
        Form.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"font-size:24px;\n"
"}\n"
"QFrame{\n"
"border-radius:15px;\n"
"background:#6495ed\n"
"}\n"
"")
        self.successMessage = QtWidgets.QFrame(Form)
        self.successMessage.setGeometry(QtCore.QRect(10, 30, 191, 41))
        self.successMessage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.successMessage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.successMessage.setObjectName("successMessage")
        self.textEdit_success = QtWidgets.QTextEdit(self.successMessage)
        self.textEdit_success.setGeometry(QtCore.QRect(60, 10, 91, 31))
        self.textEdit_success.setObjectName("textEdit_success")
        self.errorMessage = QtWidgets.QFrame(Form)
        self.errorMessage.setGeometry(QtCore.QRect(160, 140, 191, 41))
        self.errorMessage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errorMessage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.errorMessage.setObjectName("errorMessage")
        self.textEdit_error = QtWidgets.QTextEdit(self.errorMessage)
        self.textEdit_error.setGeometry(QtCore.QRect(50, 10, 121, 31))
        self.textEdit_error.setObjectName("textEdit_error")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit_success.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'century gothic\'; font-size:24px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Giriş Başarılı</span></p></body></html>"))
        self.textEdit_error.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'century gothic\'; font-size:24px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Giriş Başarısız!!!</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
