# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_product(object):
    def setupUi(self, product):
        product.setObjectName("product")
        product.resize(606, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(product)
        self.stackedWidget.setGeometry(QtCore.QRect(120, 70, 321, 131))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_product_type = QtWidgets.QWidget()
        self.page_product_type.setObjectName("page_product_type")
        self.pushButton_product_type = QtWidgets.QPushButton(self.page_product_type)
        self.pushButton_product_type.setGeometry(QtCore.QRect(120, 50, 75, 23))
        self.pushButton_product_type.setObjectName("pushButton_product_type")
        self.stackedWidget.addWidget(self.page_product_type)
        self.page_2_product_color = QtWidgets.QWidget()
        self.page_2_product_color.setObjectName("page_2_product_color")
        self.pushButton_2_product_color = QtWidgets.QPushButton(self.page_2_product_color)
        self.pushButton_2_product_color.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_2_product_color.setObjectName("pushButton_2_product_color")
        self.stackedWidget.addWidget(self.page_2_product_color)
        self.page_3_product_number = QtWidgets.QWidget()
        self.page_3_product_number.setObjectName("page_3_product_number")
        self.pushButton_3_product_number = QtWidgets.QPushButton(self.page_3_product_number)
        self.pushButton_3_product_number.setGeometry(QtCore.QRect(120, 60, 75, 23))
        self.pushButton_3_product_number.setObjectName("pushButton_3_product_number")
        self.stackedWidget.addWidget(self.page_3_product_number)

        self.retranslateUi(product)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(product)

    def retranslateUi(self, product):
        _translate = QtCore.QCoreApplication.translate
        product.setWindowTitle(_translate("product", "Form"))
        self.pushButton_product_type.setText(_translate("product", "ürün typr"))
        self.pushButton_2_product_color.setText(_translate("product", "ürün rengi"))
        self.pushButton_3_product_number.setText(_translate("product", "ürün adedi "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    product = QtWidgets.QWidget()
    ui = Ui_product()
    ui.setupUi(product)
    product.show()
    sys.exit(app.exec_())
